# Generated by Django 5.0.6 on 2026-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=24)),
                ('score', models.PositiveIntegerField()),
                ('wave_reached', models.PositiveSmallIntegerField(default=1)),
                ('words_solved', models.PositiveSmallIntegerField(default=0)),
                ('asteroids_smashed', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['-score'], name='scores_scor_score_542fd0_idx'), models.Index(fields=['-created_at'], name='scores_scor_created_5b9d91_idx')],
            },
        ),
    ]
